In [1]:
import pandas as pd

In [27]:
data = pd.read_csv('data_books.csv')

#drop Unnamed: 0  

data = data.drop(['Unnamed: 0'],axis=1 )
#data = data.drop(['Unnamed: 0' ],axis=1)

#product_name

#product price

# product stock

# product avaliation

#product category

#datetime

data['scrapy_datetime'] = pd.to_datetime(data['scrapy_datetime'])

In [26]:
data.sample(10)

,product_name,product_price,product_stock,product_avaliation,product_category,scrapy_datetime
33,the_last_girl_(the_dominion_trilogy_#1),36.26,instock,2,science fiction,2022-05-05 15:40:42
47,the_long_haul_(diary_of_a_wimpy_kid_#9),44.07,instock,1,humor,2022-05-05 15:49:41
17,emma,32.93,instock,2,classics,2022-05-05 15:36:34
40,quench_your_own_thirst:_business_lessons_learn...,43.14,instock,1,business,2022-05-05 15:51:30
31,do_androids_dream_of_electric_sheep?_(blade_ru...,51.48,instock,1,science fiction,2022-05-05 15:40:42
35,the_dirty_little_secrets_of_getting_your_dream...,33.34,instock,4,business,2022-05-05 15:51:30
39,made_to_stick:_why_some_ideas_survive_and_othe...,38.85,instock,5,business,2022-05-05 15:51:30
30,dune_(dune_#1),54.86,instock,1,science fiction,2022-05-05 15:40:42
1,the_metamorphosis,28.58,instock,1,classics,2022-05-05 15:36:34
19,mesaerion:_the_best_science_fiction_stories_18...,37.59,instock,1,science fiction,2022-05-05 15:40:42

In [30]:
# convent data to csv

data.to_csv('data.store_book.csv')